/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Information about an active nightly update for the list endpoint.
 */
export interface ActiveUpdateSummary {

  /**
   * Duration since the update started in seconds
   */
  duration_seconds: number;

  /**
   * The request ID for this update
   */
  request_id: string;

  /**
   * When the update was started
   */
  started_at: string;

  /**
   * Current status of the update
   */
  status: string;

  /**
   * Total number of symbols being processed
   */
  symbols_count: number;
}
