/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Model for analysis period information.
 */
export interface AnalysisPeriod {

  /**
   * End date of the analysis period
   */
  end_date: string;

  /**
   * Start date of the analysis period
   */
  start_date: string;
}
