/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnalysisPeriod } from '../models/analysis-period';
import { OverallStatistics } from '../models/overall-statistics';
import { SymbolCompletenessData } from '../models/symbol-completeness-data';

/**
 * Response model for data completeness analysis.
 */
export interface DataCompletenessResponse {

  /**
   * Start and end dates of the analysis
   */
  analysis_period: AnalysisPeriod;

  /**
   * Overall completeness statistics
   */
  overall_statistics: OverallStatistics;

  /**
   * Recommendations for improving data completeness
   */
  recommendations?: Array<string>;

  /**
   * Completeness statistics for each symbol
   */
  symbol_completeness: {
[key: string]: SymbolCompletenessData;
};

  /**
   * Symbols that need immediate attention due to data issues
   */
  symbols_needing_attention?: Array<string>;
}
