/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request model for data completeness analysis.
 */
export interface DataCompletenessRequest {

  /**
   * Automatically attempt to fill detected gaps
   */
  auto_fill_gaps?: boolean;

  /**
   * End date for analysis
   */
  end_date: string;

  /**
   * Whether to include detailed validation results
   */
  include_details?: boolean;

  /**
   * Maximum number of gaps to attempt filling per symbol
   */
  max_gap_fill_attempts?: number;

  /**
   * Start date for analysis
   */
  start_date: string;

  /**
   * Symbols to analyze
   */
  symbols: Array<string>;
}
