/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Summary statistics for the nightly update operation.
 */
export interface NightlyUpdateSummary {

  /**
   * Earliest start date across all symbol updates
   */
  earliest_start_date?: (string | null);

  /**
   * Number of failed updates
   */
  failed_updates: number;

  /**
   * Latest end date across all symbol updates
   */
  latest_end_date?: (string | null);

  /**
   * Total candles created per timeframe across all symbols
   */
  resampling_summary?: {
[key: string]: number;
};

  /**
   * Number of successful updates
   */
  successful_updates: number;

  /**
   * Number of symbols with validation errors
   */
  symbols_with_validation_errors?: number;

  /**
   * Total 1-minute candles updated across all symbols
   */
  total_candles_updated?: number;

  /**
   * Total resampled candles created across all symbols
   */
  total_resampled_candles?: number;

  /**
   * Total number of symbols processed
   */
  total_symbols: number;

  /**
   * Total number of validation errors
   */
  total_validation_errors?: number;

  /**
   * Total duration of the update process
   */
  update_duration_seconds: number;
}
