/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NightlyUpdateSummary } from '../models/nightly-update-summary';
import { SymbolUpdateResult } from '../models/symbol-update-result';

/**
 * Response model for nightly update endpoint.
 */
export interface NightlyUpdateResponse {

  /**
   * When the update process completed
   */
  completed_at: string;

  /**
   * Global errors that affected the entire operation
   */
  global_errors?: Array<string>;

  /**
   * Maximum concurrent updates that were used
   */
  max_concurrent_used: number;

  /**
   * Whether the overall operation was successful
   */
  overall_success: boolean;

  /**
   * Unique identifier for this update request
   */
  request_id: string;

  /**
   * When the update process started
   */
  started_at: string;

  /**
   * Summary of the update operation
   */
  summary: NightlyUpdateSummary;

  /**
   * Detailed results for each symbol
   */
  symbol_results: {
[key: string]: SymbolUpdateResult;
};

  /**
   * Symbols that were actually processed
   */
  symbols_processed: Array<string>;

  /**
   * Symbols that were requested for update
   */
  symbols_requested?: (Array<string> | null);
}
