/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request model for nightly update endpoint.
 */
export interface NightlyUpdateRequest {

  /**
   * Whether to automatically resample to other timeframes after 1min update
   */
  enable_resampling?: boolean;

  /**
   * Optional end date for the update range. If not provided, defaults to yesterday (current date - 1 day)
   */
  end_date?: (string | null);

  /**
   * Whether to validate existing data before updating
   */
  force_validation?: boolean;

  /**
   * Maximum number of concurrent symbol updates. If not provided, uses setting default. Must be greater than 0.
   */
  max_concurrent?: (number | null);

  /**
   * Optional start date for the update range. If not provided, automatically determines based on last update date
   */
  start_date?: (string | null);

  /**
   * Optional list of symbols to update. If not provided, uses default symbol lists from settings
   */
  symbols?: (Array<string> | null);
}
