/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderSide } from '../models/order-side';
import { OrderType } from '../models/order-type';

/**
 * Individual order model representing a trading instruction.
 */
export interface Order {

  /**
   * Entry price for limit orders (ignored for market orders)
   */
  entry_price?: (number | null);

  /**
   * ISO 8601 timestamp when the order should be entered
   */
  entry_time: string;

  /**
   * Order type: MKT (market) or LMT (limit)
   */
  entry_type: OrderType;

  /**
   * Order side: buy or sell
   */
  side: OrderSide;

  /**
   * Stop loss price level
   */
  stop_loss?: (number | null);

  /**
   * Take profit price level
   */
  take_profit?: (number | null);
}
