/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Model for overall completeness statistics.
 */
export interface OverallStatistics {

  /**
   * Overall completeness percentage across all symbols
   */
  overall_completeness_percentage: number;

  /**
   * Total actual candles across all symbols
   */
  total_actual_candles: number;

  /**
   * Total expected candles across all symbols
   */
  total_expected_candles: number;

  /**
   * Total missing candles across all symbols
   */
  total_missing_candles: number;

  /**
   * Total number of symbols analyzed
   */
  total_symbols: number;

  /**
   * Total trading days across all symbols
   */
  total_trading_days: number;

  /**
   * Total valid days across all symbols
   */
  total_valid_days: number;
}
