/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Pagination information for data series.
 */
export interface PaginationInfo {

  /**
   * Whether there is a next page
   */
  has_next: boolean;

  /**
   * Whether there is a previous page
   */
  has_previous: boolean;

  /**
   * Current page number (1-based)
   */
  page: number;

  /**
   * Number of items per page
   */
  page_size: number;

  /**
   * Total number of items available
   */
  total_items: number;

  /**
   * Total number of pages
   */
  total_pages: number;
}
