/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationInfo } from '../models/pagination-info';
import { PriceCandle } from '../models/price-candle';
import { Timeframe } from '../models/timeframe';

/**
 * Collection of price candles for a specific symbol and timeframe.
 */
export interface PriceDataSeries {

  /**
   * List of price candles
   */
  candles: Array<PriceCandle>;

  /**
   * End date of the series
   */
  end_date?: (string | null);

  /**
   * Pagination information (when paginated)
   */
  pagination?: (PaginationInfo | null);

  /**
   * Start date of the series
   */
  start_date?: (string | null);

  /**
   * Trading symbol (e.g., AAPL, MSFT)
   */
  symbol: string;

  /**
   * Timeframe (e.g., 1min, 5min, daily)
   */
  timeframe: Timeframe;
}
