/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Individual price candle model representing OHLCV data.
 *
 * This matches the format returned by Financial Modeling Prep API:
 * {
 *     "date": "2025-07-03 12:59:00",
 *     "open": 213.57,
 *     "low": 213.32,
 *     "high": 213.69,
 *     "close": 213.58,
 *     "volume": 670856
 * }
 */
export interface PriceCandle {

  /**
   * Closing price
   */
  close: string;

  /**
   * Timestamp of the candle
   */
  date: string;

  /**
   * Highest price
   */
  high: string;

  /**
   * Lowest price
   */
  low: string;

  /**
   * Opening price
   */
  open: string;

  /**
   * Trading volume
   */
  volume: string;
}
