/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Progress information for a nightly update.
 */
export interface ProgressInfo {

  /**
   * Number of symbols completed
   */
  completed_symbols: number;

  /**
   * Current processing step
   */
  current_step: string;

  /**
   * Currently processing symbol
   */
  current_symbol?: (string | null);

  /**
   * Estimated time remaining in seconds
   */
  estimated_time_remaining_seconds?: (number | null);

  /**
   * Overall progress percentage
   */
  progress_percentage: number;

  /**
   * List of symbols currently being processed
   */
  symbols_in_progress?: Array<string>;

  /**
   * Total number of symbols to process
   */
  total_symbols: number;
}
