/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Performance metrics for the simulation.
 */
export interface SimulationMetrics {

  /**
   * Average return per trade as a percentage
   */
  avg_trade_return: number;

  /**
   * Number of orders that were successfully executed
   */
  executed_orders: number;

  /**
   * Calculate the execution rate (executed orders / total orders).
   */
  execution_rate: number;

  /**
   * Calculate the loss rate (1 - win_rate).
   */
  loss_rate: number;

  /**
   * Maximum drawdown as a percentage (negative value)
   */
  max_drawdown: number;

  /**
   * Total number of orders submitted
   */
  total_orders: number;

  /**
   * Total profit and loss across all trades
   */
  total_pnl: number;

  /**
   * Percentage of winning trades (0.0 to 1.0)
   */
  win_rate: number;
}
