/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SimulationMetrics } from '../models/simulation-metrics';
import { Timeframe } from '../models/timeframe';
import { Trade } from '../models/trade';

/**
 * Complete response model for the trading simulation.
 */
export interface SimulationResponse {

  /**
   * End time of the simulation window
   */
  end: string;

  /**
   * Performance metrics for the simulation
   */
  metrics: SimulationMetrics;

  /**
   * Calculate the simulation duration in days.
   */
  simulation_duration_days: number;

  /**
   * Start time of the simulation window
   */
  start: string;

  /**
   * Trading symbol that was simulated
   */
  symbol: string;

  /**
   * Timeframe used for the simulation
   */
  timeframe: Timeframe;

  /**
   * List of executed trades with their results
   */
  trades: Array<Trade>;

  /**
   * Calculate the average number of trades per day.
   */
  trades_per_day: number;
}
