/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Order } from '../models/order';
import { Timeframe } from '../models/timeframe';

/**
 * Request model for the trading simulation endpoint.
 */
export interface SimulationRequest {

  /**
   * End time for the simulation window (ISO 8601)
   */
  end: string;

  /**
   * List of orders to simulate
   */
  orders: Array<Order>;

  /**
   * Start time for the simulation window (ISO 8601)
   */
  start: string;

  /**
   * Trading symbol (e.g., AAPL, MSFT)
   */
  symbol: string;

  /**
   * Candle timeframe for simulation
   */
  timeframe: Timeframe;
}
