/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ValidationResultModel } from '../models/validation-result-model';

/**
 * Model for symbol-specific completeness data.
 */
export interface SymbolCompletenessData {

  /**
   * Average completeness percentage per day
   */
  average_daily_completeness?: number;

  /**
   * Best single day completeness percentage
   */
  best_day_completeness?: number;

  /**
   * Total number of candles recovered through gap filling
   */
  candles_recovered?: number;

  /**
   * Percentage of data completeness
   */
  completeness_percentage: number;

  /**
   * Number of days with data gaps
   */
  days_with_gaps?: number;

  /**
   * Number of full trading days (390 candles expected)
   */
  full_days_count?: number;

  /**
   * Whether gap filling was attempted
   */
  gap_fill_attempted?: boolean;

  /**
   * Number of gaps filled successfully
   */
  gaps_filled_successfully?: number;

  /**
   * Number of gaps where vendor data is unavailable
   */
  gaps_vendor_unavailable?: number;

  /**
   * Number of half trading days (210 candles expected)
   */
  half_days_count?: number;

  /**
   * Number of days with invalid data
   */
  invalid_days: number;

  /**
   * Number of missing candles
   */
  missing_candles: number;

  /**
   * Total actual number of candles found
   */
  total_actual_candles: number;

  /**
   * Total expected number of candles
   */
  total_expected_candles: number;

  /**
   * Total number of gaps found
   */
  total_gaps_found?: number;

  /**
   * Total number of distinct missing periods
   */
  total_missing_periods?: number;

  /**
   * Total trading days in the period
   */
  total_trading_days: number;

  /**
   * Number of days with valid data
   */
  valid_days: number;

  /**
   * Detailed validation results (if requested)
   */
  validation_results?: (Array<ValidationResultModel> | null);

  /**
   * Worst single day completeness percentage
   */
  worst_day_completeness?: number;
}
