/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Progress information for a single symbol.
 */
export interface SymbolProgress {

  /**
   * When processing completed
   */
  completed_at?: (string | null);

  /**
   * Current processing step
   */
  current_step: string;

  /**
   * Error message if failed
   */
  error_message?: (string | null);

  /**
   * Symbol progress percentage
   */
  progress_percentage: number;

  /**
   * When processing started
   */
  started_at?: (string | null);

  /**
   * Current status (pending, validating, downloading, resampling, completed,              failed)
   */
  status: string;

  /**
   * Trading symbol
   */
  symbol: string;
}
