/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Supported timeframes for price data and simulation.
 */
export enum Timeframe {
  $1Min = '1min',
  $5Min = '5min',
  $15Min = '15min',
  $30Min = '30min',
  $1H = '1h',
  $2H = '2h',
  $4H = '4h',
  Daily = 'daily'
}
