/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderSide } from '../models/order-side';
import { TradeResult } from '../models/trade-result';

/**
 * Individual trade result model.
 */
export interface Trade {

  /**
   * Price at which the trade was entered
   */
  entry_price: number;

  /**
   * Timestamp when the trade was entered
   */
  entry_time: string;

  /**
   * Price at which the trade was exited
   */
  exit_price: number;

  /**
   * Timestamp when the trade was exited
   */
  exit_time: string;

  /**
   * Duration the position was held in minutes
   */
  holding_minutes: number;

  /**
   * Determine if this is a winning trade.
   */
  is_winning_trade: boolean;

  /**
   * Profit and loss for this trade
   */
  pnl: number;

  /**
   * Trade exit reason: tp (take profit), sl (stop loss), or timeout
   */
  result: TradeResult;

  /**
   * Calculate the return percentage for this trade.
   */
  return_percentage: number;

  /**
   * Trade side: buy or sell
   */
  side: OrderSide;
}
