/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgressInfo } from '../models/progress-info';
import { SymbolProgress } from '../models/symbol-progress';

/**
 * Response model for get_update_progress_details endpoint.
 */
export interface UpdateProgressDetailsResponse {

  /**
   * Overall progress information
   */
  overall_progress: ProgressInfo;

  /**
   * The request ID for this update
   */
  request_id: string;

  /**
   * Progress information for each symbol
   */
  symbol_progress: {
[key: string]: SymbolProgress;
};
}
