/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NightlyUpdateSummary } from '../models/nightly-update-summary';
import { ProgressInfo } from '../models/progress-info';

/**
 * Response model for get_update_status endpoint.
 */
export interface UpdateStatusResponse {

  /**
   * When the update completed (only for completed updates)
   */
  completed_at?: (string | null);

  /**
   * Whether the update is complete
   */
  is_complete: boolean;

  /**
   * Overall success status (only for completed updates)
   */
  overall_success?: (boolean | null);

  /**
   * Progress information
   */
  progress: ProgressInfo;

  /**
   * The request ID for this update
   */
  request_id: string;

  /**
   * When the update was started
   */
  started_at: string;

  /**
   * Current status of the update
   */
  status: string;

  /**
   * Summary information (only for completed updates)
   */
  summary?: (NightlyUpdateSummary | null);

  /**
   * Total number of symbols being processed
   */
  symbols_count: number;
}
