/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateStatusResponse } from '../../models/update-status-response';

export interface GetUpdateStatusNightlyUpdateStatusRequestIdGet$Params {
  request_id: string;
}

export function getUpdateStatusNightlyUpdateStatusRequestIdGet(http: HttpClient, rootUrl: string, params: GetUpdateStatusNightlyUpdateStatusRequestIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getUpdateStatusNightlyUpdateStatusRequestIdGet.PATH, 'get');
  if (params) {
    rb.path('request_id', params.request_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateStatusResponse>;
    })
  );
}

getUpdateStatusNightlyUpdateStatusRequestIdGet.PATH = '/nightly-update/status/{request_id}';
