/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NightlyUpdateRequest } from '../../models/nightly-update-request';

export interface StartNightlyUpdateNightlyUpdateStartPost$Params {
      body: NightlyUpdateRequest
}

export function startNightlyUpdateNightlyUpdateStartPost(http: HttpClient, rootUrl: string, params: StartNightlyUpdateNightlyUpdateStartPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, startNightlyUpdateNightlyUpdateStartPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

startNightlyUpdateNightlyUpdateStartPost.PATH = '/nightly-update/start';
